/* Generated by Yosys 0.9+1706 (git sha1 2ce7a0d3, clang 6.0.0-1ubuntu2 -fPIC -Os) */

(* top =  1  *)
(* src = "top.v:1" *)
module top(clk, rst, q);
  wire [3:0] _00_;
  (* unused_bits = "0" *)
  wire _01_;
  (* unused_bits = "0" *)
  wire _02_;
  (* unused_bits = "0" *)
  wire _03_;
  (* unused_bits = "0" *)
  wire _04_;
  (* unused_bits = "0" *)
  wire _05_;
  (* unused_bits = "0" *)
  wire [3:0] _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  (* src = "top.v:2" *)
  input clk;
  (* src = "top.v:3" *)
  output [3:0] q;
  (* src = "top.v:2" *)
  input rst;
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:35" *)
  INV _11_ (
    .I(_08_),
    .O(_00_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "top.v:7|/usr/local/bin/../share/yosys/xilinx/arith_map.v:294" *)
  CARRY4 _12_ (
    .CI(1'h0),
    .CO({ _05_, _04_, _03_, _02_ }),
    .CYINIT(1'h0),
    .DI({ 3'h0, _08_ }),
    .O({ _00_[3:1], _01_ }),
    .S({ _06_[3:1], _00_[0] })
  );
  BUFG _13_ (
    .I(_10_),
    .O(_09_)
  );
  (* keep = 32'd1 *)
  IBUF _14_ (
    .I(clk),
    .O(_10_)
  );
  (* keep = 32'd1 *)
  OBUF _15_ (
    .I(_08_),
    .O(q[0])
  );
  (* keep = 32'd1 *)
  OBUF _16_ (
    .I(_06_[1]),
    .O(q[1])
  );
  (* keep = 32'd1 *)
  OBUF _17_ (
    .I(_06_[2]),
    .O(q[2])
  );
  (* keep = 32'd1 *)
  OBUF _18_ (
    .I(_06_[3]),
    .O(q[3])
  );
  (* keep = 32'd1 *)
  IBUF _19_ (
    .I(rst),
    .O(_07_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "top.v:5|/usr/local/bin/../share/yosys/xilinx/xc7_ff_map.v:123" *)
  FDRE #(
    .INIT(1'hx)
  ) _20_ (
    .C(_09_),
    .CE(1'h1),
    .D(_00_[0]),
    .Q(_08_),
    .R(_07_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "top.v:5|/usr/local/bin/../share/yosys/xilinx/xc7_ff_map.v:123" *)
  FDRE #(
    .INIT(1'hx)
  ) _21_ (
    .C(_09_),
    .CE(1'h1),
    .D(_00_[1]),
    .Q(_06_[1]),
    .R(_07_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "top.v:5|/usr/local/bin/../share/yosys/xilinx/xc7_ff_map.v:123" *)
  FDRE #(
    .INIT(1'hx)
  ) _22_ (
    .C(_09_),
    .CE(1'h1),
    .D(_00_[2]),
    .Q(_06_[2]),
    .R(_07_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "top.v:5|/usr/local/bin/../share/yosys/xilinx/xc7_ff_map.v:123" *)
  FDRE #(
    .INIT(1'hx)
  ) _23_ (
    .C(_09_),
    .CE(1'h1),
    .D(_00_[3]),
    .Q(_06_[3]),
    .R(_07_)
  );
endmodule
